### ISSUE TITLE
Schedule Notification

### ISSUE THREAD

**Issue by matteopiccioni** [tmt242001/Plugin.LocalNotification#1]
Hello is possibile to schedule notification for a future date?
Will this notification persist after phone reboot?
Thanks for your plugin!

**Comment by matteopiccioni** [comment]
Thanks for answer

**Comment by tmt242001** [comment]
Now it is possible to Schedule local notification.
https://www.nuget.org/packages/Plugin.LocalNotification/2.0.0

**Comment by agusibrahim** [comment]
hi @thudugala how about repeat the schedule? examples are repeated every day
