### ISSUE TITLE
[iOS] Badge not get cleared after reading the notification

### ISSUE THREAD

**Issue by masonyc** [tmt242001/Plugin.LocalNotification#11]
**Describe the bug**
Badge on app is not cleared after reading the local notification

**To Reproduce**
1. Send some local notification.
2. Read it.
3. Badge still hangs on app icon

**Expected behavior**
Badge should be cleared

**Platform (please complete the following information):**
 - OS: iOS
 - Version 10+

**Comment by SagarPanwala** [comment]
@thudugala  I can see 1 bug may be related to this, App is not resetting badge count at all after the app. Even though in sample we have code to ResetBadgeNumber when app comes to foreground
