### ISSUE TITLE
Plugin.LocalNotification and System.ServiceModel can't be together in the same project 

### ISSUE THREAD

**Issue by someelse** [tmt242001/Plugin.LocalNotification#14]
**Describe the bug**
Plugin.LocalNotification  and System.ServiceModel can't be together in the same project 

**To Reproduce**
When I include wcf service to my project , the dependence for: System.ServeceModel.Duplex + System.ServeceModel.Http + System.ServeceModel.NetTcp + System.ServeceModel.Security and 73 compile Error popup !!!
All of them are in App.Android project at Recource.Designer.cs file.
See error: 
Severity Code Description Project File Line Suppression State
Error CS0102 The type 'Resource.Id' already contains a definition for 'main' LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6482 Active
Error CS0145 A const field requires a value to be provided LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6323 Active
Error CS1003 Syntax error, ',' expected LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6323 Active
Error CS1002 ; expected LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6323 Active
Error CS1519 Invalid token '=' in class, struct, or interface member declaration LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6323 Active
Error CS1519 Invalid token '=' in class, struct, or interface member declaration LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6323 Active
Error CS0145 A const field requires a value to be provided LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6326 Active
Error CS1003 Syntax error, ',' expected LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6326 Active
Error CS1002 ; expected LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6326 Active
Error CS1519 Invalid token '=' in class, struct, or interface member declaration LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6326 Active
Error CS1519 Invalid token '=' in class, struct, or interface member declaration LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6326 Active
Error CS0145 A const field requires a value to be provided LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6422 Active
Error CS1003 Syntax error, ',' expected LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6422 Active
Error CS1002 ; expected LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6422 Active
Error CS1519 Invalid token '=' in class, struct, or interface member declaration LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6422 Active
Error CS1519 Invalid token '=' in class, struct, or interface member declaration LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6422 Active
Error CS0145 A const field requires a value to be provided LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6425 Active
Error CS1003 Syntax error, ',' expected LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6425 Active
Error CS1002 ; expected LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6425 Active
Error CS1519 Invalid token '=' in class, struct, or interface member declaration LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6425 Active
Error CS1519 Invalid token '=' in class, struct, or interface member declaration LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6425 Active
Error CS0145 A const field requires a value to be provided LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6479 Active
Error CS1003 Syntax error, ',' expected LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6479 Active
Error CS1002 ; expected LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6479 Active
Error CS1519 Invalid token '=' in class, struct, or interface member declaration LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6479 Active
Error CS1519 Invalid token '=' in class, struct, or interface member declaration LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6479 Active
Error CS0145 A const field requires a value to be provided LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6482 Active
Error CS1003 Syntax error, ',' expected LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6482 Active
Error CS1002 ; expected LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6482 Active
Error CS1519 Invalid token '=' in class, struct, or interface member declaration LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6482 Active
Error CS1519 Invalid token '=' in class, struct, or interface member declaration LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6482 Active
Error CS0145 A const field requires a value to be provided LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6485 Active
Error CS1003 Syntax error, ',' expected LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6485 Active
Error CS1002 ; expected LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6485 Active
Error CS1519 Invalid token '=' in class, struct, or interface member declaration LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6485 Active
Error CS1519 Invalid token '=' in class, struct, or interface member declaration LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6485 Active
Error CS0145 A const field requires a value to be provided LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6488 Active
Error CS1003 Syntax error, ',' expected LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6488 Active
Error CS1002 ; expected LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6488 Active
Error CS1519 Invalid token '=' in class, struct, or interface member declaration LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6488 Active
Error CS1519 Invalid token '=' in class, struct, or interface member declaration LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6488 Active
Error CS0145 A const field requires a value to be provided LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6764 Active
Error CS1003 Syntax error, ',' expected LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6764 Active
Error CS1002 ; expected LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6764 Active
Error CS1519 Invalid token '=' in class, struct, or interface member declaration LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6764 Active
Error CS1519 Invalid token '=' in class, struct, or interface member declaration LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6764 Active
Error CS0145 A const field requires a value to be provided LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6767 Active
Error CS1003 Syntax error, ',' expected LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6767 Active
Error CS1002 ; expected LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6767 Active
Error CS1519 Invalid token '=' in class, struct, or interface member declaration LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6767 Active
Error CS1519 Invalid token '=' in class, struct, or interface member declaration LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6767 Active
Error CS0145 A const field requires a value to be provided LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6770 Active
Error CS1003 Syntax error, ',' expected LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6770 Active
Error CS1002 ; expected LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6770 Active
Error CS1519 Invalid token '=' in class, struct, or interface member declaration LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6770 Active
Error CS1519 Invalid token '=' in class, struct, or interface member declaration LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6770 Active
Error CS0102 The type 'Resource.Id' already contains a definition for 'bottomtab' LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6326 Active
Error CS0102 The type 'Resource.Id' already contains a definition for 'flyoutcontent' LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6425 Active
Error CS0102 The type 'Resource.Id' already contains a definition for 'main' LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6485 Active
Error CS0102 The type 'Resource.Id' already contains a definition for 'main' LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6488 Active
Error CS0102 The type 'Resource.Id' already contains a definition for 'shellcontent' LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6767 Active
Error CS0102 The type 'Resource.Id' already contains a definition for 'shellcontent' LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6770 Active
Error IDE1007 The name 'navarea' does not exist in the current context. LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6323 Active
Error IDE1007 The name 'tabbar' does not exist in the current context. LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6326 Active
Error IDE1007 The name 'appbar' does not exist in the current context. LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6422 Active
Error IDE1007 The name 'recycler' does not exist in the current context. LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6425 Active
Error IDE1007 The name 'appbar' does not exist in the current context. LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6479 Active
Error IDE1007 The name 'scrollview' does not exist in the current context. LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6482 Active
Error IDE1007 The name 'tablayout' does not exist in the current context. LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6485 Active
Error IDE1007 The name 'toolbar' does not exist in the current context. LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6488 Active
Error IDE1007 The name 'appbar' does not exist in the current context. LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6764 Active
Error IDE1007 The name 'scrollview' does not exist in the current context. LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6767 Active
Error IDE1007 The name 'toolbar' does not exist in the current context. LocalNotification.Sample.Android D:\Desktop\Sample\NuGet\Sample.Android\obj\Debug\90\designtime\Resource.designer.cs 6770 Active
**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
 - OS: [e.g. iOS] windows 10
 - Version [e.g. 22]  2.0.7

**Smartphone (please complete the following information):**

**Additional context**

Here's the sample project , from this site, with the Compile errors
[Sample.zip](https://github.com/tmt242001/Plugin.LocalNotification/files/2907040/Sample.zip)

**Comment by tmt242001** [comment]
Cannot reproduce the error. The attached sample project can be compiled without any issue.

`
1>------ Rebuild All started: Project: LocalNotification.Sample, Configuration: Debug Any CPU ------
1>LocalNotification.Sample -> C:\Users\ElvinT\source\repos\temp\Sample\NuGet\Sample\bin\Debug\netstandard2.0\LocalNotification.Sample.dll
2>------ Rebuild All started: Project: LocalNotification.Sample.Android, Configuration: Debug Any CPU ------
2>  LocalNotification.Sample.Android -> C:\Users\ElvinT\source\repos\temp\Sample\NuGet\Sample.Android\bin\Debug\LocalNotification.Sample.Android.dll
2>  No way to resolve conflict between "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e". Choosing "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" arbitrarily.
========== Rebuild All: 2 succeeded, 0 failed, 0 skipped ==========
`
![image](https://user-images.githubusercontent.com/4112014/53440888-71b2d300-3a6a-11e9-9440-618d6f25e842.png)

**Comment by someelse** [comment]
The build process succeesded but....Errors, and i'm Worry......

![err](https://user-images.githubusercontent.com/48019243/53475771-7763e500-3a79-11e9-8b31-90294d3585c2.png)

with the emulator Android_Accelerated_x86_Oreo (Android 8.1 - Api 27) the Error count raise to 73
![err2](https://user-images.githubusercontent.com/48019243/53476397-f73e7f00-3a7a-11e9-9137-3e53056b299d.png)

**Comment by someelse** [comment]
hi,
Is there any solution for this problem ?

בהצלחה
דורית

**Comment by someelse** [comment]
Hi,
Is there any solution for this problem ?




‪On Thu, 14 Mar 2019 at 13:44, ‫דורית בן-דוד‬‎ <bddorit1@gmail.com> wrote:‬

> hi,
> Is there any solution for this problem ?
>
> בהצלחה
> דורית
>
>
> On Tue, 26 Feb 2019 at 21:34, Elvin (Tharindu) Thudugala <

**Comment by tmt242001** [comment]
@someelse  can you please clarify that you can built the project, if you reference System.ServiceModel and Plugin.LocalNotification separately. 

Also, you tried building after deleting bin and obj folders ?
