### ISSUE TITLE
Is scheduled recurring notification possible with this plugin? 

### ISSUE THREAD

**Issue by Druffl3** [tmt242001/Plugin.LocalNotification#15]
For example, If I set a notification to pop at 18:30. Is it possible for my app to pop a notification at 18;30, everyday till I disable that particular notification?

**Comment by tmt242001** [comment]
Is it possible for my app to pop a notification at 18:30?
**Yes**
Everyday till I disable that particular notification?
**No**, notification will only fire ones

**Comment by thudugala** [comment]
In Android, JobScheduler is used for scheduling. 

JobScheduler can be:
- Delayed to run at a specific DateTime
- Set to repeart at a specific TimeSpan

But **NOT** both at the same time.
