### ISSUE TITLE
Notifications working but no alert sound

### ISSUE THREAD

**Issue by kelvin195eclipse** [tmt242001/Plugin.LocalNotification#4]
Hi,

First of all, thanks and appreciate for the effort of creating this plugin, it is working in anywhere accept no alert sound or ring when notification appears, seeking fo help.

Thank you =)

**Comment by tmt242001** [comment]
Hi, can you check your device settings ? 

![screenshot_20181017-083524](https://user-images.githubusercontent.com/4112014/47042568-146b6300-d1e8-11e8-9676-cb08cf6ebf00.png)

![screenshot_20181017-083542](https://user-images.githubusercontent.com/4112014/47042577-1a614400-d1e8-11e8-99e6-a3eea8c731f5.png)

**Comment by tmt242001** [comment]
Assume issue if fix now

**Comment by nbsoftware** [comment]
Hello,
Still no sound for me on iOS 12 with latest version of the plugin.
Am I missing something?
(Sound is there on Android)

**Comment by tmt242001** [comment]
Hi @nbsoftware, do you know the last good version that it worked ?

**Comment by nbsoftware** [comment]
Halas, I only discovered your plugin today and started to use it.
Works really great apart from this annoying no sound in iOS.
I have not used any other version than the latest 2.0.3.
Sorry to not being more helpful.

**Comment by masonyc** [comment]
> Halas, I only discovered your plugin today and started to use it.
> Works really great apart from this annoying no sound in iOS.
> I have not used any other version than the latest 2.0.3.
> Sorry to not being more helpful.

I have tested it out in the sample project and it does make some sound. When you test it, is the application in background state? If the application is open then it will only shows the notification without making any sound. This is the default notification design by Apple.

**Comment by tmt242001** [comment]
https://developer.apple.com/documentation/uikit/uilocalnotification

When the system delivers a local notification, several things can happen, depending on the app state and the type of notification. If the app is **not** frontmost and visible, the system displays the alert message, badges the app, and plays a sound

**Comment by nbsoftware** [comment]
Aaaah... I've test extensively (not so easy for me to trigger the local notification while in the background but I did succeed eventually) and you are right!
On iOS, sound is played *only* when app is not in foreground.
My bad.
Many thanks for the precision and great working component compared to many other buggy implementations out there.
Keep up the good work!
